### ISSUE TITLE
Where can I find  sources of binaries/ ?

### ISSUE THREAD

**Issue by dokodokoR** [antmicro/renode-board-visualization#2]

**Comment by dokodokoR** [comment]
I would like to do visualizations of other sensors using scripts/ and binaries/ as a reference, so I would like the source code of binaries/.

**Comment by PiotrZierhoffer** [comment]
Hi @dokodokoR 

The blinky sample is just a standard Zephyr sample: https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/basic/blinky built for `arduino_nano_33_ble` target.

The person detection - you can see a CI working here: https://github.com/antmicro/tensorflow-arduino-examples/

The specific sample code is here: https://github.com/tensorflow/tflite-micro-arduino-examples/tree/main/examples/person_detection

**Comment by dokodokoR** [comment]
@PiotrZierhoffer 
Thank you!  I will use it.
